### ISSUE TITLE
Missing factor in the PerturbedMultiplicative perturbation

### ISSUE THREAD

**Issue by BatyLeo** [axelparmentier/InferOpt.jl#81] opened 2023-07-03 13:02 UTC
According to the paper, `θ_perturbed = θ .* exp.(ε .* Z .- ε^2)` ([here](https://github.com/axelparmentier/InferOpt.jl/blob/b9f4f69f1214338c54399fe4e00fa45e10b65e75/src/perturbed/multiplicative.jl#L55)) should be `θ_perturbed = θ .* exp.(ε .* Z .- ε^2 / 2)` instead

**Comment by gdalle** [comment] 2023-07-03 15:16
Duplicate of #82

**Closed** 2023-07-03 15:24 UTC
Labels: bug
